const SET_ACTIVE_NODES_GROUPS = 'SET_ACTIVE_NODES_GROUPS'
const SET_ACTIVE_EDGES_GROUPS = 'SET_ACTIVE_EDGES_GROUPS'
const ADD_GROUP_MEMBERS = 'ADD_GROUP_MEMBERS'

export default {
  SET_ACTIVE_NODES_GROUPS,
  SET_ACTIVE_EDGES_GROUPS,
  ADD_GROUP_MEMBERS
}
