const UPDATE_NODES = 'UPDATE_NODES'
const UPDATE_EDGES = 'UPDATE_EDGES'
const ADD_GROUP_MEMBERS = 'ADD_GROUP_MEMBERS'
const DATA_UPDATE = 'DATA_UPDATE'

export default {
  UPDATE_NODES,
  UPDATE_EDGES,
  ADD_GROUP_MEMBERS,
  DATA_UPDATE
}
